# Generated by Django 5.0.3 on 2024-03-29 21:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Categoriya nomi')),
                ('icon', models.CharField(max_length=255, verbose_name='Icona')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram', models.CharField(max_length=100, verbose_name='Telegram link')),
                ('phone', models.CharField(help_text='998990001122', max_length=12, verbose_name='Tel raqam')),
            ],
        ),
        migrations.CreateModel(
            name='Costumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=20, verbose_name='Ismi')),
                ('last_name', models.CharField(max_length=20, null=True, verbose_name='Familyasi')),
                ('phone', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Your phone number must start with 9 and not exceed 12 characters. For example: 998901234567', regex='^998([3578]{2}|(9[013-57-9]))\\d{7}$')], verbose_name='tel raqami')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Organizatsiya Nomi')),
                ('discription', models.TextField(verbose_name='Malumot')),
                ('address', models.CharField(max_length=250, verbose_name='Address')),
                ('individual', models.BooleanField(default=False, verbose_name='Jismony shaxs')),
                ('legal_entity', models.BooleanField(default=False, verbose_name='Yuridik shaxs')),
                ('long', models.CharField(max_length=9, unique=True, verbose_name='Kordinata x')),
                ('lat', models.CharField(max_length=9, unique=True, verbose_name='Kordinata y')),
                ('costumer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi User')),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Nomi')),
                ('discription', models.TextField(verbose_name="Ma'lumot")),
                ('phone', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message="Raqam tug'ri kiriting For example: 998901234567", regex='^998([3578]{2}|(9[013-57-9]))\\d{7}$')], verbose_name='Tel raqam')),
                ('telegram_status', models.BooleanField(default=False, verbose_name='Telegram bormi?')),
                ('telegram', models.CharField(blank=True, max_length=40, null=True, verbose_name='Telegram Username')),
                ('salary_status', models.BooleanField(default=False, verbose_name='Maosh suxbat asosida bulsa')),
                ('min_salary', models.FloatField(verbose_name='Maosh narxi minimal')),
                ('max_salary', models.FloatField(verbose_name='Maosh narxi maksimal')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilish vaqti')),
                ('sub_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.category', verbose_name='Kategory')),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.organization', verbose_name='Organizatsiya')),
            ],
        ),
    ]
