# Generated by Django 5.0.3 on 2024-03-29 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_topwishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='max_salary',
            field=models.FloatField(blank=True, null=True, verbose_name='Maosh narxi maksimal'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='min_salary',
            field=models.FloatField(blank=True, null=True, verbose_name='Maosh narxi minimal'),
        ),
    ]
