# Generated by Django 5.0.3 on 2024-03-29 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_alter_announcement_max_salary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costumer',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='costumer',
            name='name',
            field=models.CharField(max_length=20, verbose_name='F.I.O'),
        ),
    ]
